baseURL: https://www.ssound.cf/
languageCode: en-us
title: Ssound
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: /logos/logo.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Make your life more fragrant …
    # Hero subtitle (optional)
    subtitle: A Freelance UI Sound Design
    # Hero image (from static/images/___)
    image: /wave.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
  #  - systek
  #  - tribe
  #  - kromo
  #  - infinite
  #  - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: ZenZyburi
    url: /#project_1
  - title: Shamdo
    url: /#project_2
  - title: TheSudoku
    url: /#project_3
  - title: Mark's Workshop
    url: /#project_4
  - title: Contact
    url: /#footer  

  section1:
    title: ZenZyburi
    subtitle: 2d point-&-click adventure quest
    image: /section_bg/zz.jpg
  
  section2:
    title: Shamdo
    subtitle: meditation and relaxation media project
    image: /section_bg/sd.jpg
  
  section3:
    title: TheSudoku
    subtitle: casual game project
    image: /section_bg/sk.jpg

  section4:
    title: Mark's Workshop
    subtitle: diferent composing
    image: /section_bg/mw.jpg


  section5: false

#  section6: 
#    title: Prj_6
#    subtitle: diferent composing


  footer:
    # Logo (from /images/logos/___)
    logo: /systek.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    # Icons are from Font Awesome

    - link: https://www.facebook.com/osolko
      icon: facebook
    - link: https://soundcloud.com/osolko
      icon: soundcloud
    - link: https://www.youtube.com/channel/UCuCA8ZHskv-oy2QYPAoU0Zg
      icon: youtube
    # - link: mailto:osolko@icloud.com
    #   icon: envelope

   
    bulmalogo: false
   
